name: proving
description: Dart unit test tools.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
 
dependencies:
  test: ^1.19.2
 
dev_dependencies:
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  spec: ^0.2.3
  matcher: ^0.12.16
 
