version: '3'

tasks:
    test:
        desc: Runs the tests for the project.
        cmd: dart test

    coverage:
        desc: Runs the tests with coverage.
        cmds:
            - dart pub global run coverage:test_with_coverage
            - dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info
            - genhtml coverage/lcov.info -o coverage/
            - open coverage/index.html

    docs:
        desc: Builds the project documentation.
        cmd: dart doc -o docs
        
    format:
        desc: Runs the code formatter on soruce and test files.
        cmd: dart format lib test

    lint: 
        desc: Runs the linter on the project.
        cmd: dart analyze

    build:
        desc: Runs everything to "build" the project - generally before publishing.
        cmds:
            - task: format
            - task: lint
            - task: test
            - task: docs